name: Deploy finops Backend to GCP Cloud Run

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  
  backend-deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      GAR_REPO: "REPOSITORY"
      BACKEND_SERVICE_NAME: "azure-finops-backend"
      REGION: "us-central1"
      PROJECT_ID: "zbala-1"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Authenticate with GCP using OIDC
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/187517077947/locations/global/workloadIdentityPools/github-pool-azure/providers/github-provider-azure "
          service_account: "github-actions-sa-azure@zbala-1.iam.gserviceaccount.com"

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for GCP Artifact Registry
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Backend Docker Image
        run: |
          docker build --no-cache -t us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/azure-finops-backend/azure-finops-backend:latest ./backend
          docker push us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/azure-finops-backend/azure-finops-backend:latest

      - name: Deploy Backend to Cloud Run
        run: |
          gcloud run deploy "${{ env.BACKEND_SERVICE_NAME }}" \
            --image=us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/azure-finops-backend/azure-finops-backend:latest \
            --platform=managed \
            --region="${{ env.REGION }}" \
            --allow-unauthenticated \
            --service-account="github-actions-sa-azure@zbala-1.iam.gserviceaccount.com" \
            --memory=4Gi 
            --set-env-vars SUBSCRIPTION_ID_1=5c5c5028-4a7e-435c-8430-6ece5f592ae2 \
            --set-env-vars TENANT_ID_1=e28d23e3-803d-418d-a720-c0bed39f77b6 \
            --set-env-vars CLIENT_ID_1=df36431f-d7d1-4bd8-abbe-20bb76a00b2a \
            --set-env-vars CLIENT_SECRET_1=L2G8Q~gkVUagZisPZDKsiOP~TGUV50F_EDughaH6 \
            --set-env-vars SUBSCRIPTION_ID_2=e21901bf-488a-4ded-b169-b694737e4c86 \
            --set-env-vars TENANT_ID_2=e28d23e3-803d-418d-a720-c0bed39f77b6 \
            --set-env-vars CLIENT_ID_2=bed76da5-75f7-4990-91a0-3ecc2131f4d8 \
            --set-env-vars CLIENT_SECRET_2=~RD8Q~Eect5uZuvEN.lCEBPow85irCJ4bt~DFaWB \
            --set-env-vars SMTP_SERVER=smtp.office365.com \
            --set-env-vars SMTP_PORT=587 \
            --set-env-vars EMAIL_USER=noreply@zionclouds.com \
            --set-env-vars EMAIL_PASSWORD=I1oveFlutter! \
            --set-env-vars RECIPIENTS=likhitha.singam@zionclouds.com,bala.nerusu@zionclouds.com

      - name: Get Cloud Run URL
        run: |
          echo "Backend URL:"
          gcloud run services describe ${{ env.BACKEND_SERVICE_NAME }} \
            --platform managed --region ${{ env.REGION }} --format="value(status.url)"

  